@startuml
'https://plantuml.com/sequence-diagram

class WordFinder{
+String fileText
-gets edited in replaceText
-gets printed in another file in createOutput

+String getText()
+void readFile()
+void replaceText()
+void createOutput()

}

class Solution45{
~WordFinder x = new WordFinder
+main()
~x.readFile()
~x.replaceText()
-x.createOutput()



}

WordFinder -->"Used in" Solution45
@enduml